### ISSUE TITLE
greenkeeper bot user still not recognized

### ISSUE THREAD

**Issue by shazron** [adobe/cla-bot#51]
The Greenkeeper PR was sent two days ago. See https://github.com/adobe/aio-cli-plugin-config/pull/25

I had a previous issue with my repos and the bot not being recognized and commented on an issue (that I can't recall now) and attributed it to perhaps a glitch -- but it's reoccurring.

![Screenshot_2019-05-01 Update conf to the latest version 🚀 by greenkeeper · Pull Request #25 · adobe aio-cli-plugin-config](https://user-images.githubusercontent.com/36107/56988538-e3221580-6bc2-11e9-9efb-9de35df7db1d.png)

**Comment by filmaj** [comment]
So the code in this repo as is explicitly ignores PRs sent from bots (see https://github.com/adobe/cla-bot/blob/master/checker/checker.js#L35-L40). This never seems to have been a problem before. If you check out e.g. this pull request's checks https://github.com/adobe/developer.adobe.com/pull/126/checks you'll see the CLA Bot didn't report any check.

Perhaps the issue is that the repo you are managing is requiring checks to pass?

I'll need to review the GitHub App API again but I'm pretty sure an HTTP 202 response from the bot is intended to signify "ignore this check request".

Let me know if you have any ideas on how to move forward. Do we blanket approve all PRs from bots from the CLA Bot's point of view?

**Comment by shazron** [comment]
I believe after you did the change for bots we didn't encounter it in our repos until greenkeeper did it's rounds again.

I think it's a matter of expectations. Since you ignore the check from the Bot, no response is sent, so the PR check is waiting. I think what I expected was a success response like from an Adobe employee, so the check passes with something like ('Bot, ok to ignore CLA check') or something. What do you think?

**Comment by filmaj** [comment]
That sounds good to me, let me whip together a PR.

**Comment by filmaj** [comment]
This project is continuously deployed, so upon merge [the changes were deployed out to runtime](https://travis-ci.com/adobe/cla-bot/builds/110590272), so it should be live. Can you confirm @shazron?

**Comment by shazron** [comment]
It works! Thank you! :)

<img width="805" alt="Screen Shot 2019-05-04 at 7 04 56 AM" src="https://user-images.githubusercontent.com/36107/57169705-f9d2a180-6e3a-11e9-8126-4fdf5fd23c71.png">
