### ISSUE TITLE
Docs PR rejected for Adobe Org member

### ISSUE THREAD

**Issue by DominikSuess** [adobe/cla-bot#85]
Title already describes it - opened PR https://github.com/AdobeDocs/experience-manager-cloud-manager.en/pull/13 but got rejected although I'm member of the Adobe Org

**Comment by filmaj** [comment]
Your membership in the Adobe org is set to private. The CLA Bot is installed on a per-org basis and thus only has additional permissions over and above standard public permissions to the orgs it is installed on. Since the PR is for AdobeDocs, the CLA bot installed on AdobeDocs can only introspect private org membership in the AdobeDocs org. This is not an issue with the bot but rather this is the permission model for GitHub Apps.

As such, your options are:

- Set your membership in the Adobe org as public.
- Join the AdobeDocs org. You can do so via the usual amp.corp.adobe.com automated github.com access request form. In this form, when you are asked which team to join, join one of the `AdobeDocs|*` teams. This will send your account an invite to the AdobeDocs org _which you will need to accept_.

Once you do either of the above, close and re-open your pull request to trigger the bot again.
